/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nwUI;

import javax.swing.*;
import Checkout.*;
import grocery.*;

/**
 *
 * @author throgers
 */
public class CartMenu extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    public CartMenu() {
        initComponents();
    }
    
    private final int _screen = 3;
    protected static DefaultListModel groceryModel;
    protected static DefaultListModel mtoModel;
    protected static double _subtotal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkoutB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        helpB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        groceryList = new javax.swing.JList<>();
        removeB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mtoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mtoList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        messageText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setText("Cart");

        checkoutB.setBackground(java.awt.SystemColor.controlHighlight);
        checkoutB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        checkoutB.setText("Check Out");
        checkoutB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutB.setFocusPainted(false);
        checkoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBActionPerformed(evt);
            }
        });

        backB.setBackground(java.awt.SystemColor.controlHighlight);
        backB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        backB.setText("Continue Shopping");
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.setFocusPainted(false);
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        helpB.setBackground(java.awt.SystemColor.controlHighlight);
        helpB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        helpB.setText("?");
        helpB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpB.setFocusPainted(false);
        helpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBActionPerformed(evt);
            }
        });

        groceryList.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        groceryList.setModel(groceryModel);
        groceryList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        groceryList.setFocusable(false);
        groceryList.setSelectionBackground(new java.awt.Color(255, 153, 204));
        groceryList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        groceryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groceryListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(groceryList);

        removeB.setBackground(java.awt.SystemColor.controlHighlight);
        removeB.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        removeB.setText("Remove");
        removeB.setActionCommand("Remove From Cart");
        removeB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeB.setEnabled(false);
        removeB.setFocusPainted(false);
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        jLabel2.setText("Grocery");

        mtoLabel.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        mtoLabel.setText("Made to Order");

        mtoList.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        mtoList.setModel(mtoModel);
        mtoList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mtoList.setFocusable(false);
        mtoList.setSelectionBackground(new java.awt.Color(255, 153, 204));
        mtoList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        mtoList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mtoListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mtoList);

        jLabel8.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel8.setText("Cart Total:");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel9.setText(String.format("$%.2f", _subtotal)
        );

        messageText.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        messageText.setForeground(new java.awt.Color(102, 0, 51));
        messageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mtoLabel)
                        .addGap(128, 128, 128))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helpB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkoutB))
                    .addComponent(messageText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(mtoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkoutB)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(helpB)
                        .addComponent(backB)
                        .addComponent(removeB)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void helpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBActionPerformed
        JFrame helpMenu = new HelpMenu();
        messageText.setText("");
        helpMenu.setVisible(true);
    }//GEN-LAST:event_helpBActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        JFrame groceryMenu = new GroceryMenu();
        BackMenu.g = groceryMenu;
        messageText.setText("");
        groceryMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void checkoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBActionPerformed
        //if customer is logged in, skip straight to estimate page
        Boolean isDelivery = Customer.getInstance().getIsDelivery();
        boolean isLoggedIn = Customer.getInstance().getHasLoggedIn();
        
        //for some reason this only works for student menu and not member
        if(isLoggedIn == true){
             if(isDelivery==null){
                 JFrame dorpMenu = new DeliverPickupMenu();
                 dorpMenu.setVisible(true);
             }else{
                 JFrame estimateMenu = new EstimateMenu();
                 estimateMenu.setVisible(true);
             }
        }else{
            JFrame loginMenu = new LoginMenu();
            loginMenu.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_checkoutBActionPerformed

    private void groceryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groceryListValueChanged
        mtoList.clearSelection();
        removeB.setEnabled(true);
        messageText.setText("");
        RemoveMenu.s = groceryList;
        RemoveMenu.m = groceryModel;
    }//GEN-LAST:event_groceryListValueChanged

    private void mtoListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mtoListValueChanged
        groceryList.clearSelection();
        removeB.setEnabled(true);
        messageText.setText("");
        RemoveMenu.s = mtoList;
        RemoveMenu.m = mtoModel;
    }//GEN-LAST:event_mtoListValueChanged

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
        RemoveMenu.l = messageText;
        RemoveMenu.subtotal = jLabel9;
        RemoveMenu removeMenu = new RemoveMenu();
        removeMenu.setVisible(true);
    }//GEN-LAST:event_removeBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JButton checkoutB;
    private javax.swing.JList<String> groceryList;
    private javax.swing.JButton helpB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel messageText;
    private javax.swing.JLabel mtoLabel;
    private javax.swing.JList<String> mtoList;
    private javax.swing.JButton removeB;
    // End of variables declaration//GEN-END:variables
}
