/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nwUI;

import javax.swing.JFrame;
import Checkout.*;
import grocery.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author liskiles
 */
public class GroceryMenu extends javax.swing.JFrame {

    /**
     * Creates new form groceryMTO
     */
    public GroceryMenu() {
        initComponents();
        _inventory=StartMenu._inventory;
    }
    
    private final int _screen = 1;
    private static ArrayList<Item> _inventory = new ArrayList<Item>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuTabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groceryList = new javax.swing.JList<>();
        descriptionText1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        addB = new javax.swing.JButton();
        viewCartB1 = new javax.swing.JButton();
        helpB1 = new javax.swing.JButton();
        itemPicture1 = new javax.swing.JLabel();
        priceText1 = new javax.swing.JLabel();
        messageText1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sandwichList = new javax.swing.JList<>();
        descriptionText2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        startB = new javax.swing.JButton();
        viewCartB2 = new javax.swing.JButton();
        helpB2 = new javax.swing.JButton();
        itemPicture2 = new javax.swing.JLabel();
        priceText2 = new javax.swing.JLabel();
        messageText2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menuTabs.setBackground(new java.awt.Color(155, 155, 180));
        menuTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuTabs.setFocusable(false);
        menuTabs.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        menuTabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menuTabsStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        groceryList.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        groceryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1 Apple", "2 Bagel", "3 Banana", "4 Beans", "5 Beef", "6 Bread", "7 Broccoli", "8 Carrots", "9 Cheerios", "10 Cheese", "11 Chicken", "12 Chips", "13 Coca Cola", "14 Cookies", "15 Corn", "16 Frosted Flakes", "17 Fruit Loops", "18 Grapes", "19 Hot Dogs", "20 Ice Cream", "21 Lettuce", "22 Lunchable", "23 Mackerel", "24 Milk", "25 Orange", "26 Pear", "27 Peas", "28 Pepsi", "29 Pork", "30 Potato", "31 Salmon", "32 Soup", "33 Tilapia", "34 Turkey" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groceryList.setFocusable(false);
        groceryList.setSelectionBackground(new java.awt.Color(255, 153, 255));
        groceryList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        groceryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groceryListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(groceryList);

        descriptionText1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        descriptionText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        priceLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        priceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        priceLabel1.setText("Price:");

        addB.setBackground(java.awt.SystemColor.controlHighlight);
        addB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        addB.setText("Add to Cart");
        addB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addB.setEnabled(false);
        addB.setFocusPainted(false);
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        viewCartB1.setBackground(java.awt.SystemColor.controlHighlight);
        viewCartB1.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        viewCartB1.setText("View Cart");
        viewCartB1.setToolTipText("Click to view cart");
        viewCartB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewCartB1.setFocusPainted(false);
        viewCartB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartB1ActionPerformed(evt);
            }
        });

        helpB1.setBackground(java.awt.SystemColor.controlHighlight);
        helpB1.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        helpB1.setText("?");
        helpB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpB1.setFocusPainted(false);
        helpB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpB1ActionPerformed(evt);
            }
        });

        priceText1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        priceText1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        messageText1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        messageText1.setForeground(new java.awt.Color(102, 0, 51));
        messageText1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewCartB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpB1))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(priceLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceText1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(descriptionText1)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addB, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(itemPicture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpB1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCartB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(itemPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descriptionText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel1)
                            .addComponent(priceText1))
                        .addGap(15, 15, 15)
                        .addComponent(messageText1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addB))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuTabs.addTab("Groceries", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        sandwichList.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        sandwichList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ham Sub", "Turkey Sub", "Veggie Sub", "Meatball Sub", "Italian Sub" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sandwichList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sandwichList.setFocusable(false);
        sandwichList.setSelectionBackground(new java.awt.Color(255, 153, 255));
        sandwichList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        sandwichList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sandwichListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(sandwichList);

        descriptionText2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        priceLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        priceLabel2.setText("Price:");

        startB.setBackground(java.awt.SystemColor.controlHighlight);
        startB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        startB.setText("Start Order");
        startB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startB.setEnabled(false);
        startB.setFocusPainted(false);
        startB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBActionPerformed(evt);
            }
        });

        viewCartB2.setBackground(java.awt.SystemColor.controlHighlight);
        viewCartB2.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        viewCartB2.setText("View Cart");
        viewCartB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewCartB2.setFocusPainted(false);
        viewCartB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartB2ActionPerformed(evt);
            }
        });

        helpB2.setBackground(java.awt.SystemColor.controlHighlight);
        helpB2.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        helpB2.setText("?");
        helpB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpB2.setFocusPainted(false);
        helpB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpB2ActionPerformed(evt);
            }
        });

        priceText2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N

        messageText2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        messageText2.setForeground(new java.awt.Color(102, 0, 51));
        messageText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewCartB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helpB2)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptionText2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(priceLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(priceText2)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(itemPicture2)
                                        .addGap(45, 45, 45))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(startB)
                                        .addGap(84, 84, 84))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(messageText2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCartB2)
                    .addComponent(helpB2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(itemPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descriptionText2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceText2)
                            .addComponent(priceLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageText2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startB))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuTabs.addTab("Made to Order Menu", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTabs)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void helpB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpB2ActionPerformed
        JFrame helpMenu = new HelpMenu();
        helpMenu.setVisible(true);
    }//GEN-LAST:event_helpB2ActionPerformed

    private void viewCartB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartB2ActionPerformed
        setGroceryListModel();
        setMtoListModel();
        updateSubtotal();
        JFrame cartMenu = new CartMenu();
        cartMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewCartB2ActionPerformed

    
    private void startBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBActionPerformed
        StartMenu.setBackScreen(_screen);
        int index = sandwichList.getSelectedIndex();
        
        Sandwich sandwich = new HamSandwich();
        switch(index){
            case 0: {
                    sandwich = new HamSandwich();
                    
                    break;
                    }
            case 1: {
                    sandwich = new TurkeySandwich();
                    
                    break;
                    }
            case 2: {
                    sandwich = new VeggieSandwich();
                    
                    break;
                    }
            case 3: {
                    sandwich = new MeatballSandwich();
                    
                    break;
                    }
            case 4: {
                    sandwich = new ItalianSandwich();
                    
                    break;
                    }
        }
        JFrame customFood = new CustomMenu(sandwich);
        CustomMenu.l = messageText2; 
        BackMenu.m = customFood;
        customFood.setVisible(true);
    }//GEN-LAST:event_startBActionPerformed

    private void helpB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpB1ActionPerformed
        JFrame helpMenu = new HelpMenu();
        helpMenu.setVisible(true);
    }//GEN-LAST:event_helpB1ActionPerformed

    private void viewCartB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartB1ActionPerformed
        setGroceryListModel();
        setMtoListModel();
        updateSubtotal();
        JFrame cartMenu = new CartMenu();
        BackMenu.c = cartMenu;
        cartMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewCartB1ActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        //add Item to cart
        int selected = groceryList.getSelectedIndex();
        Cart cart = Cart.getInstance();
        Item selectedItem=null;
        int inventorySize = _inventory.size();
        if(inventorySize>=selected){
            selectedItem = _inventory.get(selected);
            cart.addItem(selectedItem);
        }
        
        
        //check cart to see if item is there
        boolean isThere = false;
        ArrayList<Item> cartCheck = cart.getItems();
        for(int i = 0;i<cartCheck.size()&&!isThere;i++){
            Item itemCheck = cartCheck.get(i);
            if(itemCheck.equals(selectedItem)){
               isThere=true; 
            }
        }
        //if yes
        if(isThere){
            messageText1.setText(selectedItem.getName()+" added to cart!");
        }else{
            messageText1.setText("Unexpected error. Please try again.");
        }
        
    }//GEN-LAST:event_addBActionPerformed

    //what happens when a list item is selected
    private void sandwichListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sandwichListValueChanged
        startB.setEnabled(true);
        int index = sandwichList.getSelectedIndex();
        switch(index){
            case 0: {priceText2.setText("$5.00");
                    descriptionText2.setText("A Ham Sandwich");
                    itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nwUI/images/hamsandwich.png")));
                    break;
                    }
            case 1: {priceText2.setText("$5.00");
                    descriptionText2.setText("A Turkey Sandwich");
                    itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nwUI/images/turkeysandwich.png")));
                    break;
                    }
            case 2: {priceText2.setText("$7.00");
                    descriptionText2.setText("A Veggie Sandwich");
                    itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nwUI/images/veggiesandwich.png")));
                    break;
                    }
            case 3: {priceText2.setText("$6.00");
                    descriptionText2.setText("A Meatball Sandwich");
                    itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nwUI/images/meatballsandwich.png")));
                    break;
                    }
            case 4: {priceText2.setText("$6.00");
                    descriptionText2.setText("An Italian Sandwich");
                    itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nwUI/images/italiansandwich.png")));
                    break;
                    }
        }
    }//GEN-LAST:event_sandwichListValueChanged

    private void groceryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groceryListValueChanged
        addB.setEnabled(true);
        messageText1.setText("");
        int index = groceryList.getSelectedIndex();
        Item selected = _inventory.get(index);
        descriptionText1.setText(selected.getDescription());
        priceText1.setText("$"+selected.getPrice());
        itemPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nwUI/images/"+selected.getImage())));
        
    }//GEN-LAST:event_groceryListValueChanged

    //what happens when user changes tabs
    private void menuTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuTabsStateChanged
        messageText1.setText("");
        messageText2.setText("");
    }//GEN-LAST:event_menuTabsStateChanged

    private void setGroceryListModel(){
        //you could of course make it so that these take arraylists as parameters and do it that way if you want
        
        //all this garbage is me creating and populating a placeholder arraylist
        Cart cart = Cart.getInstance();
        ArrayList<Item> cartList = cart.getItems();
        
        //start actual method
        String toAdd = "";
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<cartList.size(); i++){
            toAdd = cartList.get(i).getName()+"      $"+cartList.get(i).getPrice();
            model.addElement(toAdd);
        }
        CartMenu.groceryModel = model;
    }
    
    private void setMtoListModel(){
        //all this garbage is me creating and populating a placeholder arraylist
        Cart cart = Cart.getInstance();
        ArrayList<Sandwich> orderList = cart.getOrders();
        
        String toAdd = "";
        //start actual method
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<orderList.size(); i++){
            double cost = orderList.get(i).cost();
            String costString = String.format("%.2f",cost);
            toAdd = orderList.get(i).getName()+"   $"+costString;
            model.addElement(toAdd);
        }
        CartMenu.mtoModel = model;
    }
    
    private void updateSubtotal(){
        double newSubtotal = 0;
        Cart cart = Cart.getInstance();
        ArrayList<Item> groceries = cart.getItems();
        ArrayList<Sandwich> orders = cart.getOrders();
        for(int i = 0;i<groceries.size();i++){
            Item toAdd = groceries.get(i);
            newSubtotal=newSubtotal+toAdd.getPrice();
        }
        for(int i = 0;i<orders.size();i++){
            Sandwich toAdd = orders.get(i);
            newSubtotal=newSubtotal+toAdd.cost();
        }
        CartMenu._subtotal = newSubtotal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroceryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroceryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroceryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroceryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroceryMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JLabel descriptionText1;
    private javax.swing.JLabel descriptionText2;
    private javax.swing.JList<String> groceryList;
    private javax.swing.JButton helpB1;
    private javax.swing.JButton helpB2;
    private javax.swing.JLabel itemPicture1;
    private javax.swing.JLabel itemPicture2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane menuTabs;
    private javax.swing.JLabel messageText1;
    private javax.swing.JLabel messageText2;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceText1;
    private javax.swing.JLabel priceText2;
    private javax.swing.JList<String> sandwichList;
    private javax.swing.JButton startB;
    private javax.swing.JButton viewCartB1;
    private javax.swing.JButton viewCartB2;
    // End of variables declaration//GEN-END:variables
}
