/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nwUI;

import javax.swing.JFrame;
import Checkout.*;
import grocery.*;

/**
 *
 * @author thmease
 */
public class LoginMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LoginMenu() {
        initComponents();
    }
    
    private final int _screen = 5;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        guestB = new javax.swing.JButton();
        memberB = new javax.swing.JButton();
        studentB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        helpB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 100));

        guestB.setBackground(java.awt.SystemColor.controlHighlight);
        guestB.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        guestB.setText("Continue as Guest");
        guestB.setToolTipText("");
        guestB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guestB.setFocusPainted(false);
        guestB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guestB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestBActionPerformed(evt);
            }
        });

        memberB.setBackground(java.awt.SystemColor.controlHighlight);
        memberB.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        memberB.setText("Member Login");
        memberB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memberB.setFocusPainted(false);
        memberB.setPreferredSize(new java.awt.Dimension(123, 23));
        memberB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBActionPerformed(evt);
            }
        });

        studentB.setBackground(java.awt.SystemColor.controlHighlight);
        studentB.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        studentB.setText("Student Login");
        studentB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentB.setFocusPainted(false);
        studentB.setPreferredSize(new java.awt.Dimension(123, 23));
        studentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBActionPerformed(evt);
            }
        });

        backB.setBackground(java.awt.SystemColor.controlHighlight);
        backB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        backB.setText("Back");
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.setFocusPainted(false);
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        helpB.setBackground(java.awt.SystemColor.controlHighlight);
        helpB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        helpB.setText("?");
        helpB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpB.setFocusPainted(false);
        helpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(helpB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backB))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(studentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(memberB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guestB, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(memberB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(guestB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpB)
                    .addComponent(backB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memberBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBActionPerformed
        StartMenu.setBackScreen(_screen);
        JFrame memberMenu = new MemberMenu();
        BackMenu.m = memberMenu;
        memberMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_memberBActionPerformed

    private void studentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBActionPerformed
        StartMenu.setBackScreen(_screen);
        JFrame studentMenu = new StudentMenu();
        BackMenu.m = studentMenu;
        studentMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_studentBActionPerformed

    private void guestBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestBActionPerformed
        StartMenu.setBackScreen(_screen);
        JFrame dorpMenu = new DeliverPickupMenu();
        BackMenu.m = dorpMenu;
        dorpMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_guestBActionPerformed

    private void helpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBActionPerformed
        JFrame helpMenu = new HelpMenu();
        helpMenu.setVisible(true);
    }//GEN-LAST:event_helpBActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        JFrame cartMenu = new CartMenu();
        BackMenu.c = cartMenu;
        cartMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JButton guestB;
    private javax.swing.JButton helpB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton memberB;
    private javax.swing.JButton studentB;
    // End of variables declaration//GEN-END:variables
}
