/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nwUI;
import Checkout.*;
import grocery.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author liskiles
 */
public class RemoveMenu extends javax.swing.JFrame {

    /**
     * Creates new form RemoveMenu
     */
    public RemoveMenu() {
        initComponents();
    }
    
    private final int _screen = 17;
    static JLabel l; //message text
    static JList s; //selected list
    static DefaultListModel m; //selected list model
    static JLabel subtotal;//subtotal text

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yesB = new javax.swing.JButton();
        noB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        yesB.setBackground(java.awt.SystemColor.controlHighlight);
        yesB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        yesB.setText("Yes");
        yesB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yesB.setFocusPainted(false);
        yesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBActionPerformed(evt);
            }
        });

        noB.setBackground(java.awt.SystemColor.controlHighlight);
        noB.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        noB.setText("No");
        noB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noB.setFocusPainted(false);
        noB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Are you sure you want to remove\n         this item from your cart?");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(yesB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(noB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesB)
                    .addComponent(noB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void yesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBActionPerformed
        //remove element from model at same index in arraylist as jlist
        //currently to check if element was removed, I'm making sure the size decreased
        //but there's a way to check if a specific object was removed if you prefer to do it that way
        //m.contains(Object)
        int initialSize = m.getSize();
        Object itemName = m.get(s.getSelectedIndex());
        m.removeElementAt(s.getSelectedIndex());
        Cart cart = Cart.getInstance();
        if(s.getModel()==CartMenu.groceryModel){
            String toBeRemoved = (String)itemName;
            ArrayList<Item> items = cart.getItems();
            boolean wasRemoved = false;
            for(int i =0; i<items.size()&&!wasRemoved;i++){
                Item check = items.get(i);
                String nameCheck = check.getName()+"      $"+check.getPrice();
                if(nameCheck.equalsIgnoreCase(toBeRemoved)){
                    items.remove(check);
                    wasRemoved = true;
                    Cart.getInstance().setItems(items);
                }
            }
        }else{
            String toBeRemoved = (String)itemName;
            ArrayList<Sandwich> orders = cart.getOrders();
            boolean wasRemoved = false;
            for(int i =0; i<orders.size()&&!wasRemoved;i++){
                Sandwich check = orders.get(i);
                String costString = String.format("%.2f",check.cost());
                String nameCheck = orders.get(i).getName()+"   $"+costString;
                if(nameCheck.equalsIgnoreCase(toBeRemoved)){
                    orders.remove(check);
                    wasRemoved = true;
                    Cart.getInstance().setOrders(orders);
                }
            }
        }
        if(initialSize>m.getSize()){
            l.setText("Removed "+itemName+" from cart.");
        }else{
            l.setText("Unexpected error. Please try again.");
        }
        updateSubtotal();
        String newSubtotal = String.format("$%.2f",CartMenu._subtotal);
        subtotal.setText(newSubtotal);
        dispose();
    }//GEN-LAST:event_yesBActionPerformed

    private void noBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBActionPerformed
        dispose();
    }//GEN-LAST:event_noBActionPerformed
    
    private void updateSubtotal(){
        double newSubtotal = 0;
        Cart cart = Cart.getInstance();
        ArrayList<Item> groceries = cart.getItems();
        ArrayList<Sandwich> orders = cart.getOrders();
        for(int i = 0;i<groceries.size();i++){
            Item toAdd = groceries.get(i);
            newSubtotal=newSubtotal+toAdd.getPrice();
        }
        for(int i = 0;i<orders.size();i++){
            Sandwich toAdd = orders.get(i);
            newSubtotal=newSubtotal+toAdd.cost();
        }
        CartMenu._subtotal = newSubtotal;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton noB;
    private javax.swing.JButton yesB;
    // End of variables declaration//GEN-END:variables
}
